### ISSUE TITLE
Riptide tridents are throwable

### ISSUE THREAD

**Issue by Viotomix** [DragonEggBedrockBreaking/VanillaDisable#14]
If this is a gamerule that I've somehow overlooked please let me know.
On mod version 3.0.2,
Game version 1.20.1
and Fabric version 0.14.21 using a Riptide trident just throws the trident instead of launching you forward.

I haven't tested this on any other version, but I did test it on it's own in singleplayer to check that it's not a compatability issue.
On multiplayer I was launched forward but the trident was thrown anyway, however that server had other mods installed. I currently don't have the means to test if I'm still launched on multiplayer with just this mod alone.

**Comment by DragonEggBedrockBreaking** [comment]
This has been fixed in the latest commit. I will close this issue when I release the mod version.

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in v3.0.3
