### ISSUE TITLE
Default Config options in 1.19.2

### ISSUE THREAD

**Issue by smamii** [DragonEggBedrockBreaking/VanillaDisable#16]
I can't seem to find any form of config for world generation in this version of the mod, so I can only assume they were only developed for later versions. It would be so incredibly helpful to have some method of having a default configuration in 1.19.2, as it is currently not worth using at all if I have to manually toggle everything before world creation every single time

**Comment by DragonEggBedrockBreaking** [comment]
The updated configuration system (the one explained in the wiki) with separate configs for worldgen and for other options, and with transferrable config files, was only available starting in 1.20. Manually having to toggle the options is an unfortunate consequence of the gamerule system of configuration. I would either have to write a new configuration format just for older versions of the game with gamerules, or backport the new configuration format to older versions.

Older versions of the mod (e.g. for 1.19.4, 1.19.2, and 1.18.2) will not get any new features, and features from newer versions of the mod will not be backported, as explained in [the wiki](https://github.com/DragonEggBedrockBreaking/VanillaDisable/wiki/Other-Versions-or-Modloaders#why-not-older-versions). Only critical bugfixes or security issues will be backported/added. At this time, 1.18.2/1.19.2/1.19.4 will not get this feature.
