### ISSUE TITLE
How can i block some structures for every world creation in that launcher instance?

### ISSUE THREAD

**Issue by Craftlgend** [DragonEggBedrockBreaking/VanillaDisable#21]
Is there a way i can have a structure always blocked for new worlds?

Or what is the code snippet that removes a single structure? ive gone through the source code, i just dont really see which of the mixin files blocks the structures from spawning

**Comment by DragonEggBedrockBreaking** [comment]
You can block structures on new worlds through the GUI in the world creation menu (next to the vanilla gamerule selection screen). The mixins controlling structure generation are the two mixin files in common/src/main/java/uk/debb/vanilla_disable/mixin/feature/worldgen/structure/

**Comment by Craftlgend** [comment]
@DragonEggBedrockBreaking thanks for the help already, really appreciate it :)
i am developing for fabric, and what irritates me that i cant find the classes referenced in the mixin injections that are in the classes you mentioned.
and how can i inject into something that doesnt exist?

**Comment by DragonEggBedrockBreaking** [comment]
> @DragonEggBedrockBreaking thanks for the help already, really appreciate it :)
> i am developing for fabric, and what irritates me that i cant find the classes referenced in the mixin injections that are in the classes you mentioned.
> and how can i inject into something that doesnt exist?

I am using mojang's official mappings ("mojmap"), while the fabric template and wiki use fabric's open source "yarn" mappings (you're probably using those), and the names are different - you'd either need to convert the mapping names (some discord servers have bots that can convert them, there are also websites like [linkie](https://linkie.shedaniel.dev/mappings?namespace=yarn&version=1.21&search=&translateMode=none)) or you'd need to use mojmap in your own project.

**Comment by Craftlgend** [comment]
> > @DragonEggBedrockBreaking thanks for the help already, really appreciate it :)
> > i am developing for fabric, and what irritates me that i cant find the classes referenced in the mixin injections that are in the classes you mentioned.
> > and how can i inject into something that doesnt exist?
> 
> I am using mojang's official mappings ("mojmap"), while the fabric template and wiki use fabric's open source "yarn" mappings (you're probably using those), and the names are different - you'd either need to convert the mapping names (some discord servers have bots that can convert them, there are also websites like [linkie](https://linkie.shedaniel.dev/mappings?namespace=yarn&version=1.21&search=&translateMode=none)) or you'd need to use mojmap in your own project.

Thank you for the advice, I’ll try it first thing tomorrow. Is it ok if I contact you here again if I should have a question to that topic again?

**Comment by DragonEggBedrockBreaking** [comment]
> > > @DragonEggBedrockBreaking thanks for the help already, really appreciate it :)
> > > i am developing for fabric, and what irritates me that i cant find the classes referenced in the mixin injections that are in the classes you mentioned.
> > > and how can i inject into something that doesnt exist?
> > 
> > I am using mojang's official mappings ("mojmap"), while the fabric template and wiki use fabric's open source "yarn" mappings (you're probably using those), and the names are different - you'd either need to convert the mapping names (some discord servers have bots that can convert them, there are also websites like [linkie](https://linkie.shedaniel.dev/mappings?namespace=yarn&version=1.21&search=&translateMode=none)) or you'd need to use mojmap in your own project.
> 
> Thank you for the advice, I’ll try it first thing tomorrow. Is it ok if I contact you here again if I should have a question to that topic again?

Yes, that's fine
