### ISSUE TITLE
Entering any other Dimension Overworld to Nether or visa versa takes way too long

### ISSUE THREAD

**Issue by bloodheaven-dev** [DragonEggBedrockBreaking/VanillaDisable#22]
Entering the Nether through the Nether Portal takes very long, even in Creative this isnt instant, it takes some time to teleport you to the Nether, same if you go to the Overworld via the Portal.

**Comment by DragonEggBedrockBreaking** [comment]
Thank you for the report, I'm looking into the issue.

**Comment by DragonEggBedrockBreaking** [comment]
Hi, I believe I have patched the issue in [this commit](https://github.com/DragonEggBedrockBreaking/VanillaDisable/commit/d51c6d3c761348bc3d621f138c5aaa882e7ecfc1). I have tested this and it seems to no longer be an issue, but please could you test it to make sure I have done it correctly? To do this, either build the mod yourself, or get a jar by going [here](https://github.com/DragonEggBedrockBreaking/VanillaDisable/actions/runs/10873473458), scrolling down to "VanillaDisable-Artifacts" and clicking on it to download (you need to be logged in to do this). Then, unzip it and grab the jar for your modloader.

**Comment by bloodheaven-dev** [comment]
> Hi, I believe I have patched the issue in [this commit](https://github.com/DragonEggBedrockBreaking/VanillaDisable/commit/d51c6d3c761348bc3d621f138c5aaa882e7ecfc1). I have tested this and it seems to no longer be an issue, but please could you test it to make sure I have done it correctly? To do this, either build the mod yourself, or get a jar by going [here](https://github.com/DragonEggBedrockBreaking/VanillaDisable/actions/runs/10873473458), scrolling down to "VanillaDisable-Artifacts" and clicking on it to download (you need to be logged in to do this). Then, unzip it and grab the jar for your modloader.

I just tested it with 1.21 Neoforge with Loader Version 21.0.167, the issue seems to be fixed.
