### ISSUE TITLE
Compatibility with Nostalgic Tweaks

### ISSUE THREAD

**Issue by bloodheaven-dev** [DragonEggBedrockBreaking/VanillaDisable#23]
Using the Custom Food Health in Nostalgic Tweaks + the predefined nutrition value adds to each other when eating food.

Example:

Setting Custom Food Health Apple: 2 Health
#Get Nutrition Value from Apple: 3 Health
/vd rule item minecraft:apple other nutrition

If you now eat the Apple you gain 5 Health instead of 2 Health from the Custom Food Health Setting in Nostalgic Tweaks
In oder to fix this issue:
/vd rule item minecraft:apple other nutrition 0

I tried to disable the mixin for that in the config\vanilla-disable-mixin.prop with following:

mixin.command.item.other.nutrition=false

However this doesn't work, am I doing it wrongly?

**Comment by DragonEggBedrockBreaking** [comment]
I believe it should be `mixin.feature.item.food=false`, please could you try that? (This is of course a temporary solution, I will look into whether a better solution is possible).

**Comment by bloodheaven-dev** [comment]
Yes this worked perfectly, I don't think it is necessary to look into a better solution due to niche. Thanks alot

**Comment by DragonEggBedrockBreaking** [comment]
Since commit https://github.com/DragonEggBedrockBreaking/VanillaDisable/commit/7a947f0a945fc5fdd029f0ee81f20ca595b77b57, the nutrition/saturation features disable themselves when nostalgic tweaks is present. I will close this issue when that feature is released. You can download the latest beta here (you need to be logged in for this to work).

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in 4.0.3 (download on Modrinth for [Fabric/Quilt](https://modrinth.com/mod/vanilla-disable/version/4.0.3) or [Neoforge](https://modrinth.com/mod/vanilla-disable/version/XhE0Pm1L)).
