### ISSUE TITLE
This mod despawns villagers

### ISSUE THREAD

**Issue by aMazeInRunar** [DragonEggBedrockBreaking/VanillaDisable#4]
All my villagers disappeared, and after a lot of testing I found out it's this mod. I don't know how or why, but it's happening.

**Comment by DragonEggBedrockBreaking** [comment]
What do you see in chat if you run `/gamerule creaturesDespawn` in game?

**Comment by DragonEggBedrockBreaking** [comment]
Also, how far away do you have to go for them to de-spawn? Is it if you go out of render distance and come back?

**Comment by aMazeInRunar** [comment]
/gamerule CreatureDespawn is set to false and it seems to despawn at exactly 128 blocks. Might I add that this is on a server running the mod including myself running the mod too.

**Comment by DragonEggBedrockBreaking** [comment]
I think I have come up with a possible solution. I am currently working on another feature, and have a lot of things on my todo list. By the end of the weak, I will *probably* have finished working on the rest of the features for the upcoming 1.1.0 release. When i get to fixing this bug, I will ask you to test again for me.

**Comment by aMazeInRunar** [comment]
Alright, thank you so much for looking into it. I really like this mod, and I'll continue to support this project, take your time! =D

**Comment by DragonEggBedrockBreaking** [comment]
Please could you try the latest commit? Do you know how to use GitHub Actions to get that build (or how to build it yourself), or would you like me to send you a jar file?

**Comment by aMazeInRunar** [comment]
I would prefer a jar file, thanks for asking =)

**Comment by DragonEggBedrockBreaking** [comment]
Do you have discord so that I can send it to you? My discord is `DragonEggBedrockBreaking#0034`, DM me there.

**Comment by aMazeInRunar** [comment]
Of course, I have sent you a request. Sorry for the delay

**Comment by DragonEggBedrockBreaking** [comment]
This has been fixed in commit 363571dc4d5778dbbd076371df8f65d818384ef6, but the gamerule doesn't seem to work. I will therefore keep this open until that is fixed.

**Comment by DragonEggBedrockBreaking** [comment]
Reverted that commit, fixed by commit b45303cc3317034461e5a22c0304c3942058d5e7
