### ISSUE TITLE
Incompatible with origins classes (startup class)

### ISSUE THREAD

**Issue by KaspianDev** [DragonEggBedrockBreaking/VanillaDisable#6]
https://gist.github.com/KaspianDev/923f13adbeca4eda78c35f0fb28c08c4

**Comment by DragonEggBedrockBreaking** [comment]
I know the issue, I will fix it in a minute.

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in 1.3.1: https://modrinth.com/mod/vanilla-disable/version/KtQKvsdu
