### ISSUE TITLE
Add: Gamerule for whether villagers restock their trades and/or how frequently

### ISSUE THREAD

**Issue by James103** [DragonEggBedrockBreaking/VanillaDisable#9]
Currently, according to the lang files of the vanilla game, "villagers restock up to two times a day." I would like a gamerule to change this frequency.

The gamerule `villagerDailyRestocks` (name subject to change) would set the number of times villagers may restock their trades in a given working day. When a villager works, if its `RestocksToday` variable is less than the value of the `villagerDailyRestocks` gamerule, it has a chance to restock its trades. The default value is `2` which preserves vanilla behavior.

My main use cases would be:
* Set `villagerDailyRestocks` to 0 to prevent villagers from automatically restocking their trades, but still allowing players to trade until their current stock is exhausted. Datapacks/scripts can still force restock a villager's trades via NBT data modification.
* Set `villagerDailyRestocks` to 1 to halve the rate at which villagers restock their trades, nerfing villager trading halls.
* Set `villagerDailyRestocks` to 2 to restore vanilla behavior.
* Set `villagerDailyRestocks` to 3 or more to allow villagers to restock more than twice in one day.

Related rules and reasons they wouldn't work for my use case:
* `villagerTradingEnabled`: Setting this to false disables ALL villager/merchant trading. Even if a datapack or script is able to force restock a villager's trades via NBT data modification, it will have no effect when that game rule is disabled.
* `infiniteTrading`: Enabling this causes the mod to restock a merchant's trades every time the trading GUI is closed, instead of just occasionally.

**Comment by DragonEggBedrockBreaking** [comment]
Added in 72a7857ad35039041316994008b403e5e8b6e381. This has not been released yet, but you can download it from GitHub Actions until then. Do you have any other ideas for this mod?

**Comment by DragonEggBedrockBreaking** [comment]
Released in v2.1.0 today.
